### ISSUE TITLE
Issues about Performance on OTB2013. 

### ISSUE THREAD

**Issue by ZSQflower** [bilylee/SiamFC-TensorFlow#2]
Hello! I tested **SiamFC-3s-color-pretrained** model on OTB2013 with your python-ported eval code. However,  the OPE AUC is about 0.5868, lower than reported 0.608 in SiamFC paper, And the tracker MEEM reachs 0.5561 while reported 0.566 in corresponding papers.   Codes for eval your tf-SiamFC: python run_trackers.py -t "SiamFC" -s cvpr13, and plot : python draw_graph.py. Is anything inconsistent with your settings? Thanks very much.

**Comment by bilylee** [comment]
Hi,

The reported 0.608 is computed using the color+gray model. Therefore, SiamFC-3s-gray-pretrained should be used for comparison instead of SiamFC-3s-color-pretrained. 

Using SiamFC-3s-gray-pretrained, the OPE AUC is 0.596. This is lower than the reported 0.608 due to platform differences (TensorFlow v.s. Matconvnet). Specifically, it is mainly caused by `tf.image.crop_and_resize` . This is a known issue and discussed [here](https://github.com/tensorflow/tensorflow/issues/6720).

Since tracking is a sequential decision problem, it is not unusual to see small errors accumulate and the tracker starts drifting.  We observe that the tracking performance of saved models in different epochs varies considerably. In tracking, ± 0.01 happens from time to time, I wouldn't worry too much about the correctness of the implementation : )

**Comment by ZSQflower** [comment]
Thank you very much.  I have acquired a lot with your code.

**Comment by bilylee** [comment]
Glad it helps : )
