### ISSUE TITLE
About VOT

### ISSUE THREAD

**Issue by zlj199502** [bilylee/SiamFC-TensorFlow#3]
Hello, I would like to ask about the issue on the VOT evaluation, why do I always suggest that there is no TraX support when testing it!

**Comment by zlj199502** [comment]
Please help me, thank you very much!

**Comment by bilylee** [comment]
Hi, 

You can check the log files in the `log` directory within the VOT workspace to find out what might cause the error. 

Several useful links are:
- [Documentation](http://www.votchallenge.net/howto/)
- [Issues](https://github.com/votchallenge/vot-toolkit/issues)
- [Support](https://groups.google.com/forum/?hl=en#!forum/votchallenge-help)

Since this repository is about the implementation of SiamFC, I will close this issue.

**Comment by zlj199502** [comment]
thankyou,please give me your email！May I ask some questions?
