### ISSUE TITLE
Why augmentation?

### ISSUE THREAD

**Issue by bliuag** [bilylee/SiamFC-TensorFlow#32]
Really a great work and clear structure! Impressed and grateful!

However, I don,t quite understand why you added augmentation to X and Z, during training and validation. If I understand correctly, the ground truth heatmap would always be Centered Gaussian. In this way, it is not reasonable to do things like random crop, right?

And during training, I do identify some inputs that does not make so much sense.

Am I missing part of your codes, or this is something we should discuss?

Thank you very much! And I mean it that this is a great work!

**Comment by bilylee** [comment]
Hi,

Thanks for your interest!

Random crop is reasonable as long as the target center in the augmented image is not far away from that in the original image. This is just case since we randomly translate the target by +- 4 pixels (crop an image with size 255 - 2 * 8 from the original image with size 255 - 8.) which is under the stride (8) of the feature extractor.
