### ISSUE TITLE
How to run benchmark

### ISSUE THREAD

**Issue by georgymh** [bilylee/SiamFC-TensorFlow#5]
Hi,

First of all, thanks a lot for porting this to TensorFlow. I was wondering if you could please provide more instructions on how to run the benchmark tests. What do I do after downloading your code [here](https://github.com/bilylee/tracker_benchmark)?

Thanks!

**Comment by georgymh** [comment]
Worked like a charm. Thanks!

**Comment by Vincent630** [comment]
> Hi,
> 
> Thanks for your interest. I have added detailed instructions for benchmark evaluation in the `Benchmark` section within README. For most of the time, simply copy and paste the commands there should be OK.

i wonder if i can resuse this benchmark for another trcker , like MDNet which is trained by tensorflow ,if that is possible what should i do to change this benchmark?because i follow the step of the readme as the SiamFC-Tensorflow which you write and i got error like this'list out of the range ',and i can evaluate the SiamFC successfully,so if you have any idea about this problem please let me know and i will appreciate  it so much. thanks a lot
